

export const CartConstants = {
    ADD_TO_CART:'ADD_TO_CART',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    ADD_QUANTITY:'ADD_QUANTITY',
    REDUCE_QUANTITY:'REDUCE_QUANTITY',
    GET_TOTAL:'GET_TOTAL',
    GET_SUBTOTAL:'GET_SUBTOTAL',

}
